[package]
name = "iceoryx2"
description = "Iceoryx2: Lock-Free Zero-Copy Interprocess Communication"
rust-version = { workspace = true }
version = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[features]
# Enables https://crates.io/crates/log as default logger
logger_log = ["iceoryx2_bb_log/logger_log"]
# Enables https://crates.io/crates/tracing as default logger
logger_tracing = ["iceoryx2_bb_log/logger_tracing"]

[dependencies]
iceoryx2_bb_container = { workspace = true }
iceoryx2_bb_system_types = { workspace = true }
iceoryx2_bb_lock_free = { workspace = true }
iceoryx2_bb_log = { workspace = true }
iceoryx2_bb_memory = { workspace = true }
iceoryx2_bb_posix = { workspace = true }
iceoryx2_bb_elementary = { workspace = true }
iceoryx2_cal = { workspace = true }

lazy_static = { workspace = true }
serde = { workspace = true }
cdr = { workspace = true }
toml = { workspace = true }
sha1_smol = { workspace = true }
tiny-fn = { workspace = true }

[dev-dependencies]
iceoryx2_bb_testing = { workspace = true }
generic-tests = { workspace = true }
